schemaVersion: 2.0.0

commandTests:
  - name: "nginx version"
    command: "nginx"
    args: ["-v"]
    expectedError: ["nginx version: nginx/1.25.*"]

  - name: "check curl is available"
    command: "which"
    args: ["curl"]
    expectedOutput: ["/usr/bin/curl"]

fileExistenceTests:
  - name: 'nginx config'
    path: '/etc/nginx/nginx.conf'
    shouldExist: true

  - name: 'app files'
    path: '/usr/share/nginx/html/index.html'
    shouldExist: true

  - name: 'health check script'
    path: '/usr/share/nginx/html/health'
    shouldExist: true

fileContentTests:
  - name: 'nginx config contains gzip'
    path: '/etc/nginx/nginx.conf'
    expectedContents: ['gzip on;']

  - name: 'nginx config contains security headers'
    path: '/etc/nginx/nginx.conf'
    expectedContents: ['X-Content-Type-Options nosniff;']

metadataTest:
  exposedPorts: ["80"]
  user: "nginx"
  workdir: "/usr/share/nginx/html"
