apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: youtube-clone-production

namespace: youtube-clone-prod

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml
  - hpa-patch.yaml

commonLabels:
  environment: production

images:
  - name: ghcr.io/sudo-hrmn/youtube-clone
    newTag: latest
