version: '3.8'

services:
  # Production build
  youtube-clone-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: youtube-clone-production
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - youtube-clone-network

  # Development build (optional)
  youtube-clone-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: youtube-clone-development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - youtube-clone-network
    profiles:
      - dev

networks:
  youtube-clone-network:
    driver: bridge

volumes:
  node_modules:
