apiVersion: v1
kind: Service
metadata:
  name: youtube-clone-service
  labels:
    app: youtube-clone
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: youtube-clone
---
apiVersion: v1
kind: Service
metadata:
  name: youtube-clone-headless
  labels:
    app: youtube-clone
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: youtube-clone
