# YouTube Clone - Secrets Configuration
# Professional secrets management with proper security practices

---
# Application Secrets
apiVersion: v1
kind: Secret
metadata:
  name: youtube-clone-secrets
  namespace: youtube-clone-v1
  labels:
    app: youtube-clone
    version: v1
    component: secrets
  annotations:
    kubernetes.io/service-account.name: youtube-clone-sa
    # External Secrets Operator annotations (if using)
    external-secrets.io/backend: vault
    external-secrets.io/key: youtube-clone/secrets
type: Opaque
data:
  # YouTube API Key (Base64 encoded)
  # Replace with actual base64 encoded API key
  YOUTUBE_API_KEY: eW91ci15b3V0dWJlLWFwaS1rZXktaGVyZQ==
  
  # Database credentials (if needed)
  DB_PASSWORD: cGFzc3dvcmQxMjM=
  DB_USERNAME: eW91dHViZWNsb25l
  
  # JWT Secret for authentication (if needed)
  JWT_SECRET: c3VwZXItc2VjcmV0LWp3dC1rZXk=
  
  # Redis password (if using Redis for caching)
  REDIS_PASSWORD: cmVkaXMtcGFzc3dvcmQ=
  
  # Third-party API keys
  ANALYTICS_API_KEY: YW5hbHl0aWNzLWFwaS1rZXk=
  MONITORING_API_KEY: bW9uaXRvcmluZy1hcGkta2V5

---
# TLS Certificates Secret
apiVersion: v1
kind: Secret
metadata:
  name: youtube-clone-tls
  namespace: youtube-clone-v1
  labels:
    app: youtube-clone
    version: v1
    component: tls
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
type: kubernetes.io/tls
data:
  # TLS certificate and key (will be populated by cert-manager)
  tls.crt: ""
  tls.key: ""

---
# Development TLS Secret
apiVersion: v1
kind: Secret
metadata:
  name: youtube-clone-dev-tls
  namespace: youtube-clone-v1
  labels:
    app: youtube-clone
    version: v1
    component: tls
    environment: development
type: kubernetes.io/tls
data:
  # Self-signed certificate for development
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t

---
# OAuth/OIDC Secrets (if using authentication)
apiVersion: v1
kind: Secret
metadata:
  name: youtube-clone-oauth-secrets
  namespace: youtube-clone-v1
  labels:
    app: youtube-clone
    version: v1
    component: oauth
type: Opaque
data:
  # Google OAuth credentials
  GOOGLE_CLIENT_ID: Z29vZ2xlLWNsaWVudC1pZA==
  GOOGLE_CLIENT_SECRET: Z29vZ2xlLWNsaWVudC1zZWNyZXQ=
  
  # GitHub OAuth credentials
  GITHUB_CLIENT_ID: Z2l0aHViLWNsaWVudC1pZA==
  GITHUB_CLIENT_SECRET: Z2l0aHViLWNsaWVudC1zZWNyZXQ=

---
# Monitoring Secrets
apiVersion: v1
kind: Secret
metadata:
  name: youtube-clone-monitoring-secrets
  namespace: youtube-clone-v1
  labels:
    app: youtube-clone
    version: v1
    component: monitoring
type: Opaque
data:
  # Prometheus credentials
  PROMETHEUS_USERNAME: cHJvbWV0aGV1cw==
  PROMETHEUS_PASSWORD: cHJvbS1wYXNzd29yZA==
  
  # Grafana credentials
  GRAFANA_ADMIN_PASSWORD: Z3JhZmFuYS1hZG1pbi1wYXNzd29yZA==
  
  # AlertManager webhook URL
  ALERTMANAGER_WEBHOOK_URL: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvLi4u
