apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-clone
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: youtube-clone
        env:
        - name: NODE_ENV
          value: "staging"
        resources:
          requests:
            memory: "96Mi"
            cpu: "75m"
          limits:
            memory: "384Mi"
            cpu: "300m"
