apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-clone
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: youtube-clone
        env:
        - name: NODE_ENV
          value: "production"
        - name: ENABLE_MONITORING
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
